steps:
  - id: "copy-dags"
    waitFor: ['-']
    name: 'google/cloud-sdk'
    dir: "./infra"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
