steps:
  - id: "copy-dags"
    waitFor: ['-']
    name: 'google/cloud-sdk'
    dir: "./infra"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
        if [ ${BRANCH_NAME} == "main" && "${_TAG}" == "prod" ]; then
          echo "deploy"
        else
          echo "don't deploy"
        fi
