steps:
  - id: "tf-plan"
    waitFor: ['-']
    name: "hashicorp/terraform:1.4.4"
    dir: "./infra"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Applying TF"
        terraform init
        terraform plan
  - id: "tf-apply"
    waitFor: ['tf-plan']
    name: "hashicorp/terraform:1.4.4"
    dir: "./infra"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Applying TF"
        terraform init
        terraform apply --auto-approve